name: graph_matching
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - numpy
    - matplotlib
    - networkx
    - jupyterlab
    - ipykernel
    - jupyterlab
    - ipython
    - ipykernel
    - scipy
