name: graph_matching2
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - numpy==1.26.4
    - matplotlib
    - jupyterlab
    - ipykernel
    - jupyterlab
    - ipython
    - ipykernel
    - scipy
    - fugw
